<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-RRJ270U" failures="1" tests="6" name="quangtester.testcase.LoginTest" time="78.085" errors="0" timestamp="2023-06-17T20:29:34 ICT" skipped="0">
  <testcase classname="quangtester.testcase.LoginTest" name="loginTestDataProvider" time="6.678">
    <failure message="Login không thành công expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Login không thành công expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at quangtester.pages.LoginPage.login(LoginPage.java:53)
at quangtester.testcase.LoginTest.loginTestDataProvider(LoginTest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- loginTestDataProvider -->
  <system-out/>
  <testcase classname="quangtester.testcase.LoginTest" name="loginTestFailure" time="12.745"/>
  <system-out/>
  <testcase classname="quangtester.testcase.LoginTest" name="loginTestDataProvider" time="14.112"/>
  <system-out/>
  <testcase classname="quangtester.testcase.LoginTest" name="loginTestExcel" time="14.838"/>
  <system-out/>
  <testcase classname="quangtester.testcase.LoginTest" name="loginTestDataProviderExcel" time="13.983"/>
  <system-out/>
  <testcase classname="quangtester.testcase.LoginTest" name="loginTestSuccessExcel" time="15.729"/>
  <system-out/>
</testsuite> <!-- quangtester.testcase.LoginTest -->
